version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: unless-stopped
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - "${GITLAB_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_PORT_REGISTRY}:8929"
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '2gb'
    networks:
      - gitlab

  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab

  gitlab-s3:
    image: 'minio/minio:RELEASE.2021-12-20T22-07-16Z'
    container_name: gitlab-s3
    restart: unless-stopped
    command: minio server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: $GITLAB_S3_USER
      MINIO_ROOT_PASSWORD: $GITLAB_S3_PASSWORD
    volumes:
      - 'gitlab_s3_data:/data'
    ports:
      - "${GITLAB_S3_PORT}:9000"
      - "${GITLAB_S3_CONSOLE_PORT}:9001"
    networks:
      - gitlab
    profiles:
      - terraform

networks:
  gitlab:

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
  gitlab_runner_config: {}
  gitlab_s3_data: {}